version: '3.8'

services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/bash -c "while sleep 1000; do :; done"
  db:
    image: postgres
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: "exit 0"
  celeryworker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: celery -A countdart.celery_app.celery_app worker --loglevel=INFO
    healthcheck:
      test: "exit 0"

volumes:
  app-db-data:
