version: '3.8'

services:
  dev:
    build:
      context: .
      target: dev
    # we need privilege to access host usb devices like cameras
    privileged: true
    volumes:
      - ./:/app
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/bash -c "while sleep 1000; do :; done"
    depends_on:
      - db
      - redis
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: "exit 0"
  celeryworker:
    build:
      context: .
      target: dev
    # we need privilege to access host usb devices like cameras
    user: root
    privileged: true
    volumes:
      - ./:/app
    command: celery -A countdart.celery_app.celery_app worker --loglevel=INFO
    healthcheck:
      test: "exit 0"
  redis:
    image: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: "exit 0"
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./:/app
    # Overrides default command so things don't shut down after the process ends.
    command: sh -c "while sleep 1000; do :; done"

volumes:
  app-db-data:
